language: node_js
os:
- windows
- linux
node_js:
- '10'
- '12'
install:
- npm version
- npm install
script:
- npm run all
after_success:
- "./node_modules/.bin/codecov"
env:
  global:
  - secure: jxctkzQt62u3EX/0n5UIzXl9z4GGOBGaoQYRYFQuenEQORrsdHGmNv3tdTwmzL0f7DEEpbfcPfloVwXW6b2m1d8hRqA87SdFrvbgcI5zS2AcAIxHYKvphIEPYb9PZc1V/GNfc8hgmjMp0yPu5goF8QYurzW4Y1nyWhZMDQugMrT/PmQ70xkpZphmy0CkZLmvzEYkRV/NVWZRbvD98Wv/5Xi/cdwDB77rgK+G8PnUemeftiicmZazt23GvtTcqiNSoswdOJnUYp8jwX+I4LNJj2zuLHfDlFyconaVhv1Hfk1QP9Rf3nQr3r1pbRn0/B/IbOFd1O7a/EwK+vwGMRo45NmO0SdcBQOVgPoCe3scl0E5Y9gAnDw5y0woQG37AFyFT4cpTSI0DWzhzJyLxa1qIn0MIT0a7R9mE9fSWwhR3jJfBVTP6oJnxTaUb3aXxNgpr4lVj6vK2QfPKMfXcuN3NhSRKX44D8+ORxmIGQmHNEzLGlsAJ5MHqiFRI/ZJy2EgHqvjavAwrgShpn6jExWWVPRgOFItVqnIRX5tQAhaReCXhqvi7ivJoH+N5p++MBVTvWpsCGzoGizB9fDnATMBTjmBR4BBNoCEdc7YGHrVAU1DXIzOCRetCJyCzwdyU1CQdJIb0WhOSLJjKyCynYCNBvjPBPo/B7oG7HxlkYzcnV8=
  - secure: aJqDUIAbJRtJ4WrwUFbUECuJcjYKwoXyJZ7q1n/0RDX/Z9zg1sBA0RY5jPV/5NsBLsAge9Fiam0x3jpHS2vAt90Pi+8jyJ5V3fOCaStihgIrkhrargpGdOeDI+JHxOwBCJ+JBWLiO5cdyFn/qgPn2SlxsgppJoLhyMUHjzVddFPH+xVIN+xS7cXSkb+j1l/gqOcGeXlBzPSQPwaLsbJxFXL9HMCV8zpRGcRAC6u6nDyonzRpBgDmIqWM9kytZHJS4leHlxcItcNkRP5R/Uv1kT2PzT9pzrVJ5gp4qo5BPtINr62je6m496Tg563Gj83DYjlijKrEzE9+fX1+llZQnZxxIDKHNTISYMHgeWrFZSEdEuZxY8zzOK5fALkll8Ma0QQMeBYW8B47/+vU1TFTveIOg4gvS4SEOsZrcF3IUX3aciQZlixCX4UfHE9uuPiKIu/5G49AD3bPChZzWXtcq6iin/tTdgqUf3CPq6ZE2JoSCprIm8KPMYIK6kUyXQ1ZZW4sVwIkrUAzNPlyYsupuBbdoXewK1hRcjkqG1x1P8R7jgN2EiO5kxZY0SEfZPjKfgW5cwhS1QJ18kM2f4BxMhkLTcMQFcuOkW0gyQFwzxLNE2sYYh5Q8bUsTdv73ABykqCPRt3BN+AbrJeltfYcmIwuJhMk8Ed5EnpOAQg9uDc=
  - secure: XYgoHTJgTMkNkaRH/DFj131Ep/R6i2JWSGRd4ZBFbkRAqq5emeiQ50Q/+h9iLdTwNGQOkmqdRNRXxohnJLQhDTn2N8zGOncAchReTZGgtJGtTSJ8hq460fQ5+qLQBjX8kB4TEYPRfVzl/xEk1baMtQNWUDElTgY6hGVxeDTvDrp5drhdJ3bWal74CYGavVUQmePU9EXseExykczdFq5FMOuxPLdJaXnprtQV/VXM3Wfab6tK7nQhxyuHvtj12Eu0yL/pND3+h50lLXWDhc94q40rCNwgLW5O9QUZnNLD322s8S3IjeVU1H2Zb3Q1o7OydNCmwoFb9fPlLV65wPPAJFE1RvAOpYrNTdEQ7jF62uDF7ckpvBOx3MH11HOVrQnW3WCgThdBw6SNME0iJTR2/tr0OuH5J/3NA3jj3Aq8N+nQ9sW7LOubVatnyhb244rChgLN//fr2yvFkEHUl0s6/lsbbn1UD/FpN2QQAgkzUN2M6GcH5kqKSnJVN+O+FrT8VMjXhLJ4s1fKJSifvg36PQvfhxAFKupaYiYqTOO9pQtrAgLJ4ocDfST0HtjvVbpukAPtPK1hCFVG8qAkvOoNGZRW43d+xxB3/5hSy3sB0hP+rSd7enz9W8htPJO5HSzOfdhVgMHpOWBaSZifjEN06kpWzJop7XsDOUMvZ8MUyqE=
